### ISSUE TITLE
Cannot delete device completely

### ISSUE THREAD

**Issue by MikOsle** [TradeFace/tuyagateway#88]
Hi
I have some issues with a Power Monitor (smart plug) and have tried to delete is from the GismoCaster in order to start all over. It seems like some configuration is cached somewhere as the tuyagateway keeps connection to the device even after deleting it.
<img width="1015" alt="Skærmbillede 2020-09-08 kl  20 36 36" src="https://user-images.githubusercontent.com/46725638/92524140-e18a4800-f221-11ea-9cc1-33d2addfb2f7.png">
How can I delete it completely?
Also, when adding it as a gismo again HA never seems to discover it.

**Comment by MikOsle** [comment]
Update!

This morning is discovered that the MQTT broker is trying to connect to a device but fails. I assume this is my power monitor.
<img width="961" alt="Skærmbillede 2020-09-09 kl  08 10 43" src="https://user-images.githubusercontent.com/46725638/92562706-afef9c00-f276-11ea-84ad-491520936a47.png">
After deleting the new Gismo (the one created after first deletion) and restarting HA I got no errors in TuyaGateway or MQTT. This was not the case yesterday where the errors kept occurring after  deleting the Gismo with no other Gismos present.

I have now added the Gismo again but I still gets the socket error in MQTT and HA do not discover the Gismo.

**Comment by Shaman2** [comment]
Now I fixed it with reinstalling mqtt brocker

**Comment by TradeFace** [comment]
Gismocaster should send a empty request to mqtt on delete. (and thus delete the entry in mqtt) Maybe it glitches sometimes. By recreating and subsequently deleting the device in gismocaster you would trigger another delete attempt. 

Your mqtt broker as a db that keeps the state. You could just stop the broker, remove the database, start the broker and restart gismocaster (so it can repopulate the broker).

**Comment by MikOsle** [comment]
I have reinstalled mqtt though it did not have any effect.

@TradeFace here do I finde the db? I am running Hassio 4.13 with mqtt and tuyagateway as addons.

**Comment by MikOsle** [comment]
I have tried to start all over with reinstalling mqtt broker, mqtt integration and tuyagateway. I did not delete the mgtt db manually though I could see in the log that mgtt did create at new db after reinstallation.
Well, after creating the gismo the situation is still the same with same log as above.

**Comment by TradeFace** [comment]
I didn't see those socket errors before. In you screenshots I see 2 different IP ranges. Are GC and Mosquitto on a different network?

**Comment by MikOsle** [comment]
Yes. They are both addons to the same Hassio running on a RPi4. I assume 172.30.33.10 is internally network of Hassio and then 192.168.68.0/24 is my home network. 192.168.68.122 vs 192.168.68.123 is just me playing with device IP to see if it did any differences.

**Comment by MikOsle** [comment]
I haven't tried anything new today but now I get following log when restarting HA. 

<img width="1342" alt="Skærmbillede 2020-09-11 kl  13 26 53" src="https://user-images.githubusercontent.com/46725638/92920590-cb9fa180-f432-11ea-8fcb-75149f9923fc.png">

**Comment by TradeFace** [comment]
The mapping in GC is probably not inline with the documentation. Check this thread https://github.com/TradeFace/tuyagateway/issues/76

**Comment by TradeFace** [comment]
No the config problem is separate from the connection problem. I haven't seen any connection problems on the mqtt side before.  You can run the gateway at debug level https://github.com/tradeface/tuyagateway/wiki//Commandline-options `-ll DEBUG`, maybe that gives you some insight into the problem.

**Comment by MikOsle** [comment]
Here you go. Let me know if any other logs are needed.

<img width="1001" alt="Skærmbillede 2020-09-12 kl  10 51 34" src="https://user-images.githubusercontent.com/46725638/92991688-f5fe6700-f4e5-11ea-9c4c-0d04dcb094c2.png">
